import Head from 'next/head'
import styles from '@/styles/PageStyles/Home.module.css'
import { useUser } from '@auth0/nextjs-auth0/client'


export default function Home() {
  const { user } = useUser()

  return (
    <>
      <Head>
        <title>Portfolio Generator</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <link href='https://fonts.googleapis.com/css?family=Lato:300,400,700' rel='stylesheet' type='text/css' />
          <div id='stars'></div>
          <div id='stars2'></div>
          <div id='stars3'></div>
          <div id='title'>
  
            <br></br>

          </div>
          <header>
          </header>
      </main>
    </>
  )
}
